### PR TITLE
Remove second polish filter since !#include is used in first

### PR DESCRIPTION
**Pull request by KonoromiHimaries**
sublist not be longer needed, because has been included

### CODE REVIEW

**Comment by KonoromiHimaries** [comment]
sublist not be longer needed, because has been included

**Comment by jspenguin2017** [comment]
The title will be in English now?

**Comment by KonoromiHimaries** [comment]
yes, most filtermainters use the english name of title

**Comment by jspenguin2017** [comment]
The problem is that the old filter will still be selected (moved to custom section). I need a way to place intervention that block specific filter lists (for reason like this and maybe known incompatibility). 

I'm curious to see what's in gorhill's mind.

**Comment by gorhill** [comment]
On my side I plan to just remove the second list when 1.15.2+ is widespread. This will create an imported list, but the alternative would be the need for new code, new delays, new chances of regression, etc., just for that one rare case for which the worst is an extra imported list. Not worth the amount of work.

**Pull request merged**
