### PR TITLE
Update assets.json

### PR DESCRIPTION
**Pull request by mat41997**
polish filters - full protect

### CODE REVIEW

**Comment by jspenguin2017** [comment]
Wow, that's quite a few... Did you ask gorhill for his opinion on this? I don't really want stuff to be bloated for no reason.

**Comment by mat41997** [comment]
@jspenguin2017 all the filters come from here
`https://www.certyficate.it/adblock/`

**Comment by jspenguin2017** [comment]
That's kind of too much, the language section is already long enough. If I will only accept one of them, which one would you recommend?

**Comment by mat41997** [comment]
@jspenguin2017 "POL: Popup Blocker PLUS" & "Popup Blocker PLUS uzupełnienie"

**Comment by jspenguin2017** [comment]
I can accept the rest once #21 lands.

**Comment by hawkeye116477** [comment]
@jspenguin2017 With this change, currently "POL: Popup Blocker PLUS" & "Popup Blocker PLUS uzupełnienie" is enabled as default for Polish users. This filter is annoyance filter, so shouldn't be enabled as default, because it removes newsletters, windows encouraging to registration, chat widgets and other annoyances, so not everybody will want it.

**Comment by jspenguin2017** [comment]
Hum... I'll remove the entries for now, I'll add them once #19 lands.

**Pull request closed without merging**
